import { IKey } from '../models/keyboard.model';

export const Keyboard_Constant: IKey[] = [
  { key: "A", usable: true, isCorrect: false },
  { key: "B", usable: true, isCorrect: false },
  { key: "C", usable: true, isCorrect: false },
  { key: "D", usable: true, isCorrect: false },
  { key: "E", usable: true, isCorrect: false },
  { key: "F", usable: true, isCorrect: false },
  { key: "G", usable: true, isCorrect: false },
  { key: "H", usable: true, isCorrect: false },
  { key: "I", usable: true, isCorrect: false },
  { key: "J", usable: true, isCorrect: false },
  { key: "K", usable: true, isCorrect: false },
  { key: "L", usable: true, isCorrect: false },
  { key: "M", usable: true, isCorrect: false },
  { key: "N", usable: true, isCorrect: false },
  { key: "O", usable: true, isCorrect: false },
  { key: "P", usable: true, isCorrect: false },
  { key: "Q", usable: true, isCorrect: false },
  { key: "R", usable: true, isCorrect: false },
  { key: "S", usable: true, isCorrect: false },
  { key: "T", usable: true, isCorrect: false },
  { key: "U", usable: true, isCorrect: false },
  { key: "V", usable: true, isCorrect: false },
  { key: "W", usable: true, isCorrect: false },
  { key: "X", usable: true, isCorrect: false },
  { key: "Y", usable: true, isCorrect: false },
  { key: "Z", usable: true, isCorrect: false },
];
